
package pkgFrames;

import DAOFactory.DAOFactory;
import Model.User;
import SeverUtils.*;
import de.javasoft.plaf.synthetica.SyntheticaBlueIceLookAndFeel;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static pkgFrames.frmMain.wsCon;

public class frmLogin extends javax.swing.JFrame {
    
    public boolean isRegister = false;
    
    public frmLogin()
    {
        initComponents();
        txtRePassword.setVisible(false);
        lblDescriptionRePassword.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackground = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        lblDescriptionUser = new javax.swing.JLabel();
        lblDescriptionPassword = new javax.swing.JLabel();
        lblDescriptionRePassword = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        txtRePassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cash Manager - Login");
        setBackground(new java.awt.Color(0, 102, 102));
        setResizable(false);

        pnlBackground.setBackground(new java.awt.Color(0, 102, 102));

        lblLogo.setBackground(new java.awt.Color(255, 255, 255));
        lblLogo.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        lblLogo.setForeground(new java.awt.Color(255, 255, 255));
        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setText("Cash Manager");

        txtUser.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        lblDescriptionUser.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        lblDescriptionUser.setForeground(new java.awt.Color(255, 255, 255));
        lblDescriptionUser.setText("Usuário");

        lblDescriptionPassword.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        lblDescriptionPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblDescriptionPassword.setText("Senha");

        lblDescriptionRePassword.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        lblDescriptionRePassword.setForeground(new java.awt.Color(255, 255, 255));
        lblDescriptionRePassword.setText("Confirmar a senha");

        btnRegister.setText("Registrar");
        btnRegister.setFocusPainted(false);
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        btnLogin.setText("Login");
        btnLogin.setToolTipText("");
        btnLogin.setFocusPainted(false);
        btnLogin.setMaximumSize(new java.awt.Dimension(77, 23));
        btnLogin.setMinimumSize(new java.awt.Dimension(77, 23));
        btnLogin.setPreferredSize(new java.awt.Dimension(77, 23));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBackgroundLayout = new javax.swing.GroupLayout(pnlBackground);
        pnlBackground.setLayout(pnlBackgroundLayout);
        pnlBackgroundLayout.setHorizontalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundLayout.createSequentialGroup()
                        .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUser)
                            .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlBackgroundLayout.createSequentialGroup()
                                .addComponent(btnRegister)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(38, 38, 38))
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDescriptionPassword)
                            .addComponent(lblDescriptionUser)
                            .addComponent(lblDescriptionRePassword)
                            .addComponent(txtRePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlBackgroundLayout.setVerticalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDescriptionUser)
                .addGap(4, 4, 4)
                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDescriptionPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(lblDescriptionRePassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegister))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
    
        if(!isRegister)
        {
            txtRePassword.setVisible(true);
            lblDescriptionRePassword.setVisible(true);
            isRegister = true;
        }
        else
        {
            if(txtPassword.getText().equals(txtRePassword.getText()) && !txtPassword.getText().equals(""))
            {
                //registra
                Model.User user = new User(txtUser.getText(), txtPassword.getText(),
                                           txtUser.getText(), 0,0);
                
                try
                {
                    DAOFactory.getUserDAO().addUser(user, wsCon.GetConnection());
                    user = DAOFactory.getUserDAO().getUser(user.getUserID(), wsCon.GetConnection());
                    Initialize(user);
                }
                catch (Exception ex)
                {
                    Logger.getLogger(frmLogin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Campos de senha não conferem",".:: Cadastro ::.",
                                              JOptionPane.OK_OPTION);
            }
        }
        
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        try
        {
            Model.User user = DAOFactory.getUserDAO().getUser(txtUser.getText(), wsCon.GetConnection());
            if(user == null)
            {
                JOptionPane.showMessageDialog(this,"Usuário ou senha inválidos",".:: Login ::.",
                                              JOptionPane.OK_OPTION);
                return;
            }
            if(user.getPassword().equals(txtPassword.getText()) && user.getUserID().equals(txtUser.getText()))
                Initialize(user);
            else
                JOptionPane.showMessageDialog(this,"Usuário ou senha inválidos",".:: Login ::.",
                                              JOptionPane.OK_OPTION);
        }
        catch (Exception ex)
        {
            Logger.getLogger(frmLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {        
        try
        {
            wsCon.SetConnection();
                  
            javax.swing.UIManager.setLookAndFeel(new SyntheticaBlueIceLookAndFeel());
        }   
        catch (Exception e)            
        {
            e.printStackTrace();
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLogin().setVisible(true);
            }
        });
    }
    private void Initialize(Model.User user)
    {    
        try
        {
            Config.setIsConnected(!wsCon.GetConnection().isClosed());
            Config.setUser(user);
                    
            frmMain fm = new frmMain();
            fm.show();
                    
            this.dispose();
        }
        catch (SQLException ex)
        {
            Logger.getLogger(frmLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel lblDescriptionPassword;
    private javax.swing.JLabel lblDescriptionRePassword;
    private javax.swing.JLabel lblDescriptionUser;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtRePassword;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
